export const MOCK_USERS = {
  torvalds: {
    login: "torvalds",
    id: 1024025,
    avatar_url: "https://avatars.githubusercontent.com/u/1024025?v=4",
    html_url: "https://github.com/torvalds",
    name: "Linus Torvalds",
    company: "Linux Foundation",
    blog: "https://kernel.org",
    location: "Portland, OR",
    email: null,
    hireable: false,
    bio: "Creator of Linux and Git. Principal Architect at the Linux Foundation.",
    twitter_username: null,
    public_repos: 12,
    public_gists: 1,
    followers: 325400,
    following: 0,
    created_at: "2011-09-03T15:26:22Z"
  },
  gaearon: {
    login: "gaearon",
    id: 810438,
    avatar_url: "https://avatars.githubusercontent.com/u/810438?v=4",
    html_url: "https://github.com/gaearon",
    name: "Dan Abramov",
    company: "Bluesky",
    blog: "https://overreacted.io",
    location: "London, UK",
    email: null,
    hireable: true,
    bio: "Working on Bluesky. Co-author of Redux, Create React App, and React core team alumni.",
    twitter_username: "dan_abramov2",
    public_repos: 260,
    public_gists: 78,
    followers: 86500,
    following: 172,
    created_at: "2011-05-25T18:18:31Z"
  },
  shadcn: {
    login: "shadcn",
    id: 124599,
    avatar_url: "https://avatars.githubusercontent.com/u/124599?v=4",
    html_url: "https://github.com/shadcn",
    name: "shadcn",
    company: null,
    blog: "https://ui.shadcn.com",
    location: "San Francisco, CA",
    email: null,
    hireable: true,
    bio: "Designing and building UI components, tools, and interfaces for the modern web.",
    twitter_username: "shadcn",
    public_repos: 54,
    public_gists: 12,
    followers: 74200,
    following: 48,
    created_at: "2009-09-10T12:00:00Z"
  },
  yyx990803: {
    login: "yyx990803",
    id: 499550,
    avatar_url: "https://avatars.githubusercontent.com/u/499550?v=4",
    html_url: "https://github.com/yyx990803",
    name: "Evan You",
    company: "VoidZero Inc.",
    blog: "https://evanyou.me",
    location: "Singapore",
    email: null,
    hireable: false,
    bio: "Creator of Vue.js, Vite, and Founder of VoidZero.",
    twitter_username: "youyuxi",
    public_repos: 180,
    public_gists: 65,
    followers: 104000,
    following: 95,
    created_at: "2010-11-28T03:00:00Z"
  },
  PrakashChokhal: {
    login: "PrakashChokhal",
    id: 13958291,
    avatar_url: "https://avatars.githubusercontent.com/u/13958291?v=4",
    html_url: "https://github.com/PrakashChokhal",
    name: "Prakash Chokhal",
    company: null,
    blog: "https://github.com/PrakashChokhal",
    location: "Nepal",
    email: null,
    hireable: true,
    bio: "Frontend Developer & Open Source Enthusiast building React, JavaScript, and modern web applications.",
    twitter_username: null,
    public_repos: 18,
    public_gists: 0,
    followers: 15,
    following: 24,
    created_at: "2023-01-15T10:00:00Z"
  }
};

export const MOCK_REPOS = {
  torvalds: [
    {
      id: 2325298,
      name: "linux",
      html_url: "https://github.com/torvalds/linux",
      description: "Linux kernel source tree",
      language: "C",
      stargazers_count: 185000,
      forks_count: 56000,
      fork: false,
      updated_at: "2026-09-28T04:00:00Z",
      homepage: "https://kernel.org"
    },
    {
      id: 2325299,
      name: "subsurface-for-dir",
      html_url: "https://github.com/torvalds/subsurface-for-dir",
      description: "Subsurface dive log program",
      language: "C++",
      stargazers_count: 1420,
      forks_count: 320,
      fork: false,
      updated_at: "2026-08-15T04:00:00Z",
      homepage: "https://subsurface-divelog.org"
    },
    {
      id: 2325300,
      name: "pesconvert",
      html_url: "https://github.com/torvalds/pesconvert",
      description: "Program for converting Brother embroidery PES files to SVG",
      language: "C",
      stargazers_count: 450,
      forks_count: 75,
      fork: false,
      updated_at: "2026-07-10T04:00:00Z",
      homepage: null
    },
    {
      id: 2325301,
      name: "test-tlb",
      html_url: "https://github.com/torvalds/test-tlb",
      description: "Small test program to test TLB performance",
      language: "C",
      stargazers_count: 380,
      forks_count: 65,
      fork: false,
      updated_at: "2026-06-01T04:00:00Z",
      homepage: null
    }
  ],
  gaearon: [
    {
      id: 38934449,
      name: "redux",
      html_url: "https://github.com/reduxjs/redux",
      description: "Predictable state container for JavaScript apps",
      language: "TypeScript",
      stargazers_count: 60500,
      forks_count: 15400,
      fork: false,
      updated_at: "2026-09-27T10:00:00Z",
      homepage: "https://redux.js.org"
    },
    {
      id: 63537249,
      name: "create-react-app",
      html_url: "https://github.com/facebook/create-react-app",
      description: "Set up a modern web app by running one command",
      language: "JavaScript",
      stargazers_count: 102000,
      forks_count: 26000,
      fork: false,
      updated_at: "2026-09-20T10:00:00Z",
      homepage: "https://create-react-app.dev"
    },
    {
      id: 15637200,
      name: "overreacted.io",
      html_url: "https://github.com/gaearon/overreacted.io",
      description: "Personal blog by Dan Abramov",
      language: "JavaScript",
      stargazers_count: 6200,
      forks_count: 1800,
      fork: false,
      updated_at: "2026-09-25T10:00:00Z",
      homepage: "https://overreacted.io"
    },
    {
      id: 23412000,
      name: "react-dnd",
      html_url: "https://github.com/react-dnd/react-dnd",
      description: "Drag and Drop for React",
      language: "TypeScript",
      stargazers_count: 20400,
      forks_count: 1900,
      fork: false,
      updated_at: "2026-08-20T10:00:00Z",
      homepage: "https://react-dnd.github.io/react-dnd"
    }
  ],
  shadcn: [
    {
      id: 59374000,
      name: "ui",
      html_url: "https://github.com/shadcn-ui/ui",
      description: "Beautifully designed components that you can copy and paste into your apps.",
      language: "TypeScript",
      stargazers_count: 78500,
      forks_count: 6200,
      fork: false,
      updated_at: "2026-09-28T02:00:00Z",
      homepage: "https://ui.shadcn.com"
    },
    {
      id: 59374001,
      name: "taxonomy",
      html_url: "https://github.com/shadcn-ui/taxonomy",
      description: "An open source application built using the new router, server components and everything new in Next.js.",
      language: "TypeScript",
      stargazers_count: 18900,
      forks_count: 2700,
      fork: false,
      updated_at: "2026-09-25T02:00:00Z",
      homepage: "https://tx.shadcn.com"
    }
  ],
  PrakashChokhal: [
    {
      id: 89012340,
      name: "Github-Profile-Viewer",
      html_url: "https://github.com/PrakashChokhal/Github-Profile-Viewer",
      description: "GitPulse — Modern developer profile analytics and repository explorer with language breakdown.",
      language: "JavaScript",
      stargazers_count: 5,
      forks_count: 1,
      fork: false,
      updated_at: "2026-09-28T05:45:00Z",
      homepage: null
    },
    {
      id: 89012341,
      name: "React-Projects-Hub",
      html_url: "https://github.com/PrakashChokhal",
      description: "Collection of interactive React 19 web applications and UI components.",
      language: "JavaScript",
      stargazers_count: 8,
      forks_count: 2,
      fork: false,
      updated_at: "2026-09-20T05:45:00Z",
      homepage: null
    },
    {
      id: 89012342,
      name: "Modern-Web-Portfolio",
      html_url: "https://github.com/PrakashChokhal",
      description: "Personal responsive developer portfolio showcasing web engineering projects.",
      language: "HTML",
      stargazers_count: 4,
      forks_count: 0,
      fork: false,
      updated_at: "2026-09-10T05:45:00Z",
      homepage: null
    }
  ]
};
